# Numpy Tricks

# np.sort

In [1]:
# code 
import numpy as np
a = np.random.randint(1,100,15)
a

array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10,  5, 14,  1],
       [97, 78, 48, 62],
       [92, 74, 71, 13],
       [38, 51, 19, 28],
       [77, 18, 36, 36],
       [ 6, 69, 98, 27]], dtype=int32)

In [3]:
np.sort(a)

array([ 1,  7,  9, 20, 21, 22, 34, 35, 43, 43, 66, 75, 90, 96, 96],
      dtype=int32)

In [ ]:
np.sort(b) # row ->sort

array([[ 1,  5, 10, 14],
       [48, 62, 78, 97],
       [13, 71, 74, 92],
       [19, 28, 38, 51],
       [18, 36, 36, 77],
       [ 6, 27, 69, 98]], dtype=int32)

In [ ]:
np.sort(b,axis=0) # column ->sort

array([[ 6,  5, 14,  1],
       [10, 18, 19, 13],
       [38, 51, 36, 27],
       [77, 69, 48, 28],
       [92, 74, 71, 36],
       [97, 78, 98, 62]], dtype=int32)

# np.append
#values append at the end

In [6]:
# code
np.append(a,200)

array([ 43,  75,   7,  66,  21,  90,   9,  20,  43,  96,  35,  34,  22,
        96,   1, 200])

In [ ]:
# adding column 
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[10.,  5., 14.,  1.,  1.],
       [97., 78., 48., 62.,  1.],
       [92., 74., 71., 13.,  1.],
       [38., 51., 19., 28.,  1.],
       [77., 18., 36., 36.,  1.],
       [ 6., 69., 98., 27.,  1.]])

# np.concatenate
#a sequence of array -> with 2D array

In [9]:
# code 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d), axis=0) # 0 is used for row 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.concatenate((c,d), axis=1) # 0 is used for column 

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
#returns an array of unique elements in the input array.

In [12]:
# code 
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [13]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims

In [14]:
# we can get the expand dimension of an array 
a

array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [16]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [17]:
np.expand_dims(a,axis=1)

array([[43],
       [75],
       [ 7],
       [66],
       [21],
       [90],
       [ 9],
       [20],
       [43],
       [96],
       [35],
       [34],
       [22],
       [96],
       [ 1]], dtype=int32)

In [19]:
np.expand_dims(a,axis=0)

array([[43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1]],
      dtype=int32)

# np.where

In [20]:
#  function returns the indices of elements in an input array where the given condition is satisfied.
a

array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [ ]:
# find greater then 50 
np.where(a>50)

(array([ 1,  3,  5,  9, 13]),)

In [22]:
# replace all values > 50 with 0 
np.where(a>50,0,a)

array([43,  0,  7,  0, 21,  0,  9, 20, 43,  0, 35, 34, 22,  0,  1],
      dtype=int32)

In [ ]:
np.where(a % 2 == 0,0,a)

array([43, 75,  7,  0, 21,  0,  9,  0, 43,  0, 35,  0,  0,  0,  1],
      dtype=int32)

# np.argmax

In [24]:
# return indices of max element of array
a

array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [25]:
b

array([[10,  5, 14,  1],
       [97, 78, 48, 62],
       [92, 74, 71, 13],
       [38, 51, 19, 28],
       [77, 18, 36, 36],
       [ 6, 69, 98, 27]], dtype=int32)

In [26]:
np.argmax(a)

np.int64(9)

In [31]:
np.argmax(b)

np.int64(22)

In [32]:
np.argmax(b,axis=0)

array([1, 1, 5, 1])

In [ ]:
np.argmax(b,axis=1) 

array([2, 0, 0, 1, 0, 2])

In [34]:
a

array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [ ]:
# np.argmin
np.argmin(a)

np.int64(14)

# np.cumsum

In [36]:
# we want to compute the comulative sum of array elements over a given axis.
a

array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [37]:
np.cumsum(a)

array([ 43, 118, 125, 191, 212, 302, 311, 331, 374, 470, 505, 539, 561,
       657, 658])

In [38]:
b

array([[10,  5, 14,  1],
       [97, 78, 48, 62],
       [92, 74, 71, 13],
       [38, 51, 19, 28],
       [77, 18, 36, 36],
       [ 6, 69, 98, 27]], dtype=int32)

In [ ]:
np.cumsum(b,axis=0)  # column 

array([[ 10,   5,  14,   1],
       [107,  83,  62,  63],
       [199, 157, 133,  76],
       [237, 208, 152, 104],
       [314, 226, 188, 140],
       [320, 295, 286, 167]])

In [ ]:
np.cumsum(b,axis=1) # Row wise

array([[ 10,  15,  29,  30],
       [ 97, 175, 223, 285],
       [ 92, 166, 237, 250],
       [ 38,  89, 108, 136],
       [ 77,  95, 131, 167],
       [  6,  75, 173, 200]])

In [42]:
# np.cumprod
np.cumprod(a)

array([                 43,                3225,               22575,
                   1489950,            31288950,          2816005500,
               25344049500,        506880990000,      21795882570000,
          2092404726720000,   73234165435200000, 2489961624796800000,
       -561076475599054848, 1476890563619389440, 1476890563619389440])

In [43]:
np.cumprod(b)

array([                  10,                   50,                  700,
                        700,                67900,              5296200,
                  254217600,          15761491200,        1450057190400,
            107304232089600,     7618600478361600,    99041806218700800,
        3763588636310630400,  7475579714746634240, -5537938009490362368,
       -7488311676053733376, -4750932771141369856,  6716930488003100672,
        2001824609887453184, -1721290338889891840,  8119002040370200576,
        6808818574257291264,  3181433623670685696, -6335012529439244288])

# np.percentile

In [44]:
# compute the nth percentile of the given data along with specified axis.
a

array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [45]:
np.percentile(a,100)

np.float64(96.0)

In [46]:
np.percentile(a,0)

np.float64(1.0)

In [47]:
np.percentile(a,58)

np.float64(43.0)

In [48]:
np.median(a)

np.float64(35.0)

# np.histogram 

In [49]:
# frequency count batata ha in a given range
a


array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [50]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90])

(array([3, 0, 3, 2, 2, 0, 1, 1, 1]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [51]:
np.histogram(a,bins=[0,50,100])

(array([10,  5]), array([  0,  50, 100]))

# np.corrcoef

In [52]:
# return pearson product moment correlation coefficients.
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin

In [53]:
# with the help of isin method , we can see that one array having value are checked in diff numpy array having diff elements with diff sizes 
a

array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [54]:
items = [10,20,30,40,50,60,70,80,90]
a[np.isin(a,items)]

array([90, 20], dtype=int32)

# np.flip

#reverse the order of array

In [55]:
a

array([43, 75,  7, 66, 21, 90,  9, 20, 43, 96, 35, 34, 22, 96,  1],
      dtype=int32)

In [56]:
np.flip(a)

array([ 1, 96, 22, 34, 35, 96, 43, 20,  9, 90, 21, 66,  7, 75, 43],
      dtype=int32)

In [57]:
b

array([[10,  5, 14,  1],
       [97, 78, 48, 62],
       [92, 74, 71, 13],
       [38, 51, 19, 28],
       [77, 18, 36, 36],
       [ 6, 69, 98, 27]], dtype=int32)

In [58]:
np.flip(b)

array([[27, 98, 69,  6],
       [36, 36, 18, 77],
       [28, 19, 51, 38],
       [13, 71, 74, 92],
       [62, 48, 78, 97],
       [ 1, 14,  5, 10]], dtype=int32)

In [59]:
np.flip(b,axis=0)

array([[ 6, 69, 98, 27],
       [77, 18, 36, 36],
       [38, 51, 19, 28],
       [92, 74, 71, 13],
       [97, 78, 48, 62],
       [10,  5, 14,  1]], dtype=int32)

In [61]:
np.flip(b,axis=1)

array([[ 1, 14,  5, 10],
       [62, 48, 78, 97],
       [13, 71, 74, 92],
       [28, 19, 51, 38],
       [36, 36, 18, 77],
       [27, 98, 69,  6]], dtype=int32)

# np.putt

In [ ]:
# in array replace the changes values by giving index number 
a

array([ 11, 110,   7,  66,  21,  90,   9,  20,  43,  96,  35,  34,  22,
        96,   1], dtype=int32)

In [63]:
np.put(a,[0,1],[11,110])

# np.delete

In [65]:
# return new array 
a

array([ 11, 110,   7,  66,  21,  90,   9,  20,  43,  96,  35,  34,  22,
        96,   1], dtype=int32)

In [68]:
np.delete(a,0)

array([110,   7,  66,  21,  90,   9,  20,  43,  96,  35,  34,  22,  96,
         1], dtype=int32)

In [70]:
np.delete(a,[1,2,3,4,5,6,7,8,9])

array([11, 35, 34, 22, 96,  1], dtype=int32)

# Set Functions
. np.union 1d
. np.intersect1d
.np.setdiff1d
.np.setxor1d
.np.in1d

In [71]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [72]:

np.intersect1d(m,n)

array([3, 4, 5])

In [73]:

np.setdiff1d(m,n)

array([1, 2])

In [74]:

np.setxor1d(m,n)

array([1, 2, 6, 7])

In [75]:

np.in1d(m,1)

C:\Users\hp\AppData\Local\Temp\ipykernel_15628\2006216917.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

# np.clip

In [76]:
# used to clip(limit) the value in any array
a

array([ 11, 110,   7,  66,  21,  90,   9,  20,  43,  96,  35,  34,  22,
        96,   1], dtype=int32)

In [77]:
np.clip(a,a_min=25, a_max=75)

array([25, 75, 25, 66, 25, 75, 25, 25, 43, 75, 35, 34, 25, 75, 25],
      dtype=int32)